### ISSUE TITLE
Reorganize code structure

### ISSUE THREAD

**Issue by shenghaoc** [AY1920S2-CS2103-W15-4/main#60]
This is of very low importance but I think eventually we should decide whether to put all the general classes in general or leave them outside of subpackages.
The omission of "Command" in the names of parsers also seems unnecessary since there are other long file names.

**Comment by limdylan** [comment]
agree, i think the general classes should be outside of subpackages (like in AB3) and i guess we could keep "Command" in class names for consistency but yea this isn't a urgent thing to do

**Comment by umaikaze** [comment]
Haha sry was lazy to type command in some of my classes will change later

**Comment by shenghaoc** [comment]
We're still creating addressbook.jar and the package name is still address 🤔

**Comment by shenghaoc** [comment]
The app icon that you can see on Windows is still for address book

**Comment by shenghaoc** [comment]
All the version warnings JavaFX caused by Scene Builder should be resolved someday
